import { Emitter } from '@rocket.chat/emitter';
import type { IWebRTCProcessor, WebRTCInternalStateMap, WebRTCProcessorConfig, WebRTCProcessorEvents } from '../../../definition';
import type { MediaStreamIdentification } from '../../../definition/media/MediaStreamIdentification';
import type { ServiceStateValue } from '../../../definition/services/IServiceProcessor';
import type { ServerMediaSignalRemoteSDP } from '../../../definition/signals';
import { MediaStreamManager } from '../../media/MediaStreamManager';
export declare class MediaCallWebRTCProcessor implements IWebRTCProcessor {
    private readonly config;
    readonly emitter: Emitter<WebRTCProcessorEvents>;
    readonly streams: MediaStreamManager;
    private peer;
    private iceGatheringTimedOut;
    private iceGatheringWaiters;
    private inputTrack;
    private screenVideoTrack;
    private _muted;
    get muted(): boolean;
    private _held;
    get held(): boolean;
    private stopped;
    private iceCandidateCount;
    private initialization;
    private _dataChannel;
    private _remoteMute;
    private _remoteHeld;
    private _dataChannelEnded;
    constructor(config: WebRTCProcessorConfig);
    setInputTrack(newInputTrack: MediaStreamTrack | null): Promise<void>;
    setScreenVideoTrack(newVideoTrack: MediaStreamTrack | null): Promise<void>;
    createOffer({ iceRestart }: {
        iceRestart?: boolean;
    }): Promise<RTCSessionDescriptionInit>;
    setMuted(muted: boolean): void;
    setHeld(held: boolean): void;
    stop(): void;
    createAnswer(): Promise<RTCSessionDescriptionInit>;
    setLocalDescription(sdp: RTCSessionDescriptionInit): Promise<void>;
    setRemoteDescription(sdp: RTCSessionDescriptionInit): Promise<void>;
    getInternalState<K extends keyof WebRTCInternalStateMap>(stateName: K): ServiceStateValue<WebRTCInternalStateMap, K>;
    getStats(selector?: MediaStreamTrack | null): Promise<RTCStatsReport | null>;
    isRemoteHeld(): boolean;
    isRemoteMute(): boolean;
    isStable(): boolean;
    getLocalDescription(): RTCSessionDescriptionInit | null;
    waitForIceGathering(): Promise<void>;
    setRemoteIds(signal: ServerMediaSignalRemoteSDP): void;
    protected combineRemoteIds(streams1: MediaStreamIdentification[], streams2: MediaStreamIdentification[]): MediaStreamIdentification[];
    protected getRemoteIdsFromSDP(sdp: string): MediaStreamIdentification[];
    getLocalStreamIds(): MediaStreamIdentification[];
    private initialize;
    private startNewGathering;
    private changeInternalState;
    private updateAudioDirectionBeforeNegotiation;
    private updateAudioDirectionAfterNegotiation;
    private updateVideoDirectionBeforeNegotiation;
    private updateVideoDirectionAfterNegotiation;
    private updateDirectionBeforeNegotiation;
    private updateDirectionAfterNegotiation;
    private reactToStoppedTransceiver;
    private requestDirection;
    private updateDirectionForVideoTrackChanged;
    private getTransceivers;
    private updateAudioDirectionWithoutNegotiation;
    private createDataChannel;
    private endDataChannel;
    private initializeDataChannel;
    private sendP2PCommand;
    private isValidCommand;
    private getCommandFromDataChannelMessage;
    private onP2PCommand;
    private setRemoteMute;
    private setRemoteHeld;
    private updateMuteForRemote;
    private processPreNegotiation;
    private processPostNegotiation;
    private updateRemoteHeld;
    private updateRemoteScreenShare;
    private registerPeerEvents;
    private unregisterPeerEvents;
    private restartIce;
    private canRenegotiate;
    private isActiveConnection;
    private onIceCandidate;
    private onIceCandidateError;
    private onNegotiationNeeded;
    private onTrack;
    private onConnectionStateChange;
    private onIceConnectionStateChange;
    private onSignalingStateChange;
    private onIceGatheringStateChange;
    private loadInputTrack;
    private loadScreenVideoTrack;
    private onIceGatheringComplete;
    private onDataChannel;
    private clearIceGatheringData;
    private clearIceGatheringWaiters;
}
//# sourceMappingURL=Processor.d.ts.map